
version: "3.8"

services:
  backend:
    build:
      context: .
    ports:
      - 5000:80
    environment:
      - MM_DB_PATH=/var/db/moviemanager
    volumes:
      - ${MM_DB_PATH:-./backend/db}:/var/db/moviemanager